-- Runs only on first cluster initialization
CREATE ROLE labread LOGIN PASSWORD 'labread' NOSUPERUSER NOCREATEDB NOCREATEROLE;
CREATE ROLE labwrite LOGIN PASSWORD 'labwrite' NOSUPERUSER NOCREATEDB NOCREATEROLE;
